# Generated by Django 3.2 on 2021-05-01 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toppings',
            old_name='name',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='toppings',
            old_name='pizza',
            new_name='topic',
        ),
    ]
